add_lunch_combo venture_flo-userdebug
add_lunch_combo venture_grouper-userdebug
add_lunch_combo venture_hammerhead-userdebug
add_lunch_combo venture_mako-userdebug
add_lunch_combo venture_shamu-userdebug

#Legacy
add_lunch_combo venture_m8-userdebug
add_lunch_combo venture_jflte-userdebug
add_lunch_combo venture_bacon-userdebug
add_lunch_combo venture_d2lte-userdebug