# Version information used on all builds
PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=LMY47I BUILD_ID=LMY47I BUILD_VERSION_TAGS=release-keys BUILD_UTC_DATE=0

# Versioning System
VENTURE_VERSION_MAJOR = 2
VENTURE_VERSION_MINOR = 1-A1
#VENTURE_VERSION_TAG = RC1

VENTURE_VERSION := $(TARGET_PRODUCT)-$(VENTURE_VERSION_MAJOR).$(VENTURE_VERSION_MINOR)-$(shell date -u +%Y%m%d)
VENTURE_MOD_VERSION := $(VENTURE_VERSION_MAJOR).$(VENTURE_VERSION_MINOR)-$(shell date -u +%Y%m%d)

PRODUCT_PROPERTY_OVERRIDES += \
  ro.venture.version=$(VENTURE_VERSION) \
  ro.mod.version=$(VENTURE_MOD_VERSION)
