# Version information used on all builds
PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=LRX22G BUILD_ID=LRX22G BUILD_VERSION_TAGS=release-keys BUILD_UTC_DATE=0

# Versioning System
VENTURE_VERSION_MAJOR = 1
VENTURE_VERSION_MINOR = 1
VENTURE_VERSION_TAG = BETA0.9

VENTURE_VERSION := $(TARGET_PRODUCT)-$(VENTURE_VERSION_MAJOR).$(VENTURE_VERSION_MINOR)-$(VENTURE_VERSION_TAG)-$(shell date -u +%Y%m%d)
VENTURE_MOD_VERSION := $(VENTURE_VERSION_MAJOR).$(VENTURE_VERSION_MINOR)-$(VENTURE_VERSION_TAG)-$(shell date -u +%Y%m%d)

PRODUCT_PROPERTY_OVERRIDES += \
  ro.venture.version=$(VENTURE_VERSION) \
  ro.mod.version=$(VENTURE_MOD_VERSION)